### ISSUE TITLE
in sonarqube6.4 Chinese Pack is not useful and not woking?

### ISSUE THREAD

**Issue by swqmaven** [SonarQubeCommunity/sonar-l10n-zh#10]
in sonarqube6.4 Chinese Pack is not useful and not woking?

**Comment by xuhuisheng** [comment]
you can referer other issues, that the l10n in sonarQube is related to the browser setup.
https://github.com/SonarQubeCommunity/sonar-l10n-zh/issues/9

**Comment by swqmaven** [comment]
@xuhuisheng thanks i had solved
