### ISSUE TITLE
add pkugin  maven  don't have any language plugin 

### ISSUE THREAD

**Issue by suxg003** [SonarQubeCommunity/sonar-l10n-zh#11]
mvn sonar:sonar \
  -Dsonar.host.url=http://127.0.0.1:9000 \
  -Dsonar.login=bf5d0066a020c41f65bc90d74ac51af180b39704

Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project sonarCloud: No quality profiles have been found, you probably don't have any language plugin installed. -> [Help 1]

**Comment by xuhuisheng** [comment]
It seems you never config sonarQube server well. The i10n plugin didn't cause this problem. The Language in the exception means that Java, JavaScript, C, or ruby, as programming language not i10n language.

**Comment by suxg003** [comment]
我的服务器 英文版没问题，版本号是
Version | 6.5.0.27846 ，安装你这个插件后报 以上错误。1.
-- | --sonar-l10n-zh-plugin-1.16.jar   sonar-l10n-zh-plugin-1.17-RC1.jar  两个版本都是同样的问题！

**Comment by suxg003** [comment]
我这边分析的java 代码

**Comment by xuhuisheng** [comment]
意思是服务器没有配置质量规则，没有安装编程语言插件，比如java，c语言的质量扫描插件。跟汉化包没关系。
检查，是否误删了plugins目录下的java语言包。

**Comment by suxg003** [comment]
FROM sonarqube

ADD sonar-l10n-zh-plugin-1.16.jar /opt/sonarqube/extensions/plugins/

嗯我是用这个docker直接加上去的

**Comment by xuhuisheng** [comment]
没用过docker镜像，原理是一样的，plugins目录下需要有对应编程语言的插件。
如果没有，应该可以通过管理后台进行安装。

**Comment by suxg003** [comment]
好的。非常感谢，我去查下，docker下的，可以参考http://www.jianshu.com/p/6cc4632628b1

**Comment by suxg003** [comment]
确实是代码分析插件的原因，已在系统更新里安装插件，非常感谢！
