### ISSUE TITLE
后台任务的banner条，不能点击其中的超链接

### ISSUE THREAD

**Issue by truebit** [SonarQubeCommunity/sonar-l10n-zh#14]
`有一个执行中的分析。<br>更多细节请查看<a href="{0}">后台任务</a>页。`

中文版展示为上面内容，感觉是没有解析成html，而是当作string直接处理了

**Comment by xuhuisheng** [comment]
已修复。
https://github.com/SonarQubeCommunity/sonar-l10n-zh/commit/4247a9fae02fe77ba7cd6d9eb460e2530272f847
