### ISSUE TITLE
project key翻译没有统一：有“关键字”，有“标识”

### ISSUE THREAD

**Issue by truebit** [SonarQubeCommunity/sonar-l10n-zh#15]
project key翻译没有统一：有“关键字”，有“标识”
在project主页面右下方是“关键字”，在project设置里面update key里面用了“标识”。其他地方没有都看。
不过感觉project key感觉翻译成“工程ID”比较好

**Comment by xuhuisheng** [comment]
感谢反馈，统一成标识感觉比较好。

**Comment by xuhuisheng** [comment]
https://github.com/SonarQubeCommunity/sonar-l10n-zh/commit/e81cc953c1a575e2f3af1b7594447625aacd91cb
