### ISSUE TITLE
感谢制作语言插件

### ISSUE THREAD

**Issue by hjkl950217** [SonarQubeCommunity/sonar-l10n-zh#20]
公司里在跑这个，明天把这个语言插件推荐给管理人员。。
感谢翻译啊！看到最近都在更新，辛苦你们啦

**Comment by xuhuisheng** [comment]
个人精力有限，细微之处还要靠大家多反馈。
感谢 @https://github.com/someja 和 @https://github.com/truebit 协助校对。

另外，汉化包可以在管理后台，插件管理中直接安装，应该不用推荐吧。
