### ISSUE TITLE
7.1 装了中文补丁还是显示英文

### ISSUE THREAD

**Issue by kanxue2002** [SonarQubeCommunity/sonar-l10n-zh#21]
![image](https://user-images.githubusercontent.com/17524255/39863007-faa88b70-5477-11e8-8e31-c086d5904ce8.png)

**Comment by xuhuisheng** [comment]
首先，安装插件之后需要重启sonar才能生效
然后，浏览器要设置为使用中文，才会显示中文。
参考：https://github.com/SonarQubeCommunity/sonar-l10n-zh/issues/9
