### ISSUE TITLE
新版本一个翻译上的小bug

### ISSUE THREAD

**Issue by WangQuan-cn** [SonarQubeCommunity/sonar-l10n-zh#23]
core_zh.properties
overview.about_this_project.TRK=关于这个西南股
原文是 about this project
应该是笔误吧
期望【关于这个项目】
version 1.21

**Comment by xuhuisheng** [comment]
感谢指正，已修复

**Comment by tonglei100** [comment]
你好，我们用的 SonarQube 7.1 版本，中文包只能更新到 1.21，还是有这个问题，能够更新支持 SonarQube 7.1，多谢
