### ISSUE TITLE
1.21版本日期的中文月有两个字？

### ISSUE THREAD

**Issue by asf-cache** [SonarQubeCommunity/sonar-l10n-zh#24]
如题

**Comment by asf-cache** [comment]
2018年6月月4日

**Comment by xuhuisheng** [comment]
请问是哪个页面有这个问题？

**Comment by asf-cache** [comment]
就是查看所有项目列表的主页，项目名称最右边有个最后扫描分析时间

**Comment by xuhuisheng** [comment]
![default](https://user-images.githubusercontent.com/1118508/42199135-52d5df0c-7ebf-11e8-83db-790b6432ac10.png)

**Comment by xuhuisheng** [comment]
是这个地方吗？sonarQube-7.2版本下没发现这个问题。

**Comment by asf-cache** [comment]
问题是我还在用7.1版本啊，1.22可以用在7.1版本上吗？

**Comment by xuhuisheng** [comment]
sonarQube-7.1对应sonar-l10n-zh-plugin-1.21

**Comment by asf-cache** [comment]
我删除了插件，重新下载，问题没有复现，有点诡异，难道是浏览器问题？
