### ISSUE TITLE
How to enable this plugin

### ISSUE THREAD

**Issue by vfaxian** [SonarQubeCommunity/sonar-l10n-zh#27]
as the subject, how to enable this plugin? I just download it and put it into the sonar_home_path/extensions/plugins, and then restart the SonarQube, but seems it didn't works, Please help.

**Comment by xuhuisheng** [comment]
First, Please restart SonarQube after install sonar-l10n-zh-plugin
Second, Please set your browser language as Chinese.
Please ref : #9

**Comment by vfaxian** [comment]
不好意思，回复的晚了，这个问题挺奇怪的，可能和OS也有关系，我的服务器是centos，本地有windows和ubuntu，但是只有ubuntu可用，其他都重启也不起作用。。。

**Comment by xuhuisheng** [comment]
1. 访问sonar，登录，进入后台配置，在应用商店里能看到sonar-zh-l10n-plugin，就说明安装成功了。
2. 如果访问还是英文，需要检查浏览器的语言配置，需要设置成中文，才能看到中文的翻译。

**Comment by vfaxian** [comment]
> 访问sonar，登录，进入后台配置，在应用商店里能看到sonar-zh-l10n-plugin，就说明安装成功了
    这个确实没问题了。

> 如果访问还是英文，需要检查浏览器的语言配置，需要设置成中文，才能看到中文的翻译
    浏览器的语言配置是中文，我昨天的意思是可能和OS有关系。IE和Chrome都不行
SonarQube： 6.7
OS： CentOS 6

**Comment by vfaxian** [comment]
please ignore this issue, it's my fault.
