### ISSUE TITLE
Cannot load this plugin 

### ISSUE THREAD

**Issue by xingyizhuce** [SonarQubeCommunity/sonar-l10n-zh#29]
I installed sonarqube7.3 on the Centos7.3.  And I installed the plugin (Chinese-pack 1.23) ,then I restarted the sonar. But it also in English. 
 I installed by web and manually, but they didn't work.
 
不论是通过web界面还是手工安装到目录下的方式都没有办法显示中文，求解

**Comment by xuhuisheng** [comment]
1. 访问sonar，登录，进入后台配置，在应用商店里能看到sonar-zh-l10n-plugin，就说明安装成功了。
2. 如果访问还是英文，需要检查浏览器的语言配置，需要设置成中文，才能看到中文的翻译。

请参考 #9 问题

**Comment by kuchaguangjie** [comment]
@xuhuisheng 修改 浏览器的 语言为 简体中文, 然后 刷新 页面 就显示成 中文了.
再修改回 English, 再刷新, 就变回 英文了.

Nice !!!
