### ISSUE TITLE
can not download plugin

### ISSUE THREAD

**Issue by 435915770** [SonarQubeCommunity/sonar-l10n-zh#39]
after click install button，it occur error.
"Error while downloading plugin 'l10nzh' with version '8.2'. No compatible plugin found."

**Comment by xuhuisheng** [comment]
估计就是网络慢，本地安装了sonar8.2，搜索chinese，显示chinese pack localization language pack for chinese版本是8.2，点击右侧的安装，提示成功后重启就成功了。
如果后台下载一直有问题，可以试试手工下载，然后复制到sonar的extensions/plugins目录下，再重启服务，下载地址：
https://github.com/SonarQubeCommunity/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-8.2/sonar-l10n-zh-plugin-8.2.jar
