### ISSUE TITLE
1.11版本的汉化包汉化不全.

### ISSUE THREAD

**Issue by flamhaze5946** [SonarQubeCommunity/sonar-l10n-zh#7]
是否是sonar改变了渲染逻辑呢, 望修复, 谢谢.

**Comment by xuhuisheng** [comment]
备注一下。
1.11支持5.6。LTS版本5.6.6貌似又进行了修改，导致汉化不全了。
以后找时间翻译一下。

**Comment by flamhaze5946** [comment]
非常感谢 :)

**Comment by xuhuisheng** [comment]
测试了sonarqube-5.6.6并创建了一个sonarqube-5.6分支，结果比较之后，差别只有两个key，说明官方就是不支持汉化的。

**Comment by xuhuisheng** [comment]
![Uploading 无标题.png…]()

**Comment by xuhuisheng** [comment]
![default](https://cloud.githubusercontent.com/assets/1118508/24955387/c9b7a80e-1fb5-11e7-853c-99a5eec64cd9.png)
下载了一个sonarqube-5.6.6，看界面都汉化了，菜单，导航都已经汉化完成了

**Comment by flamhaze5946** [comment]
好的, 我试试, 谢啦

**Comment by xuhuisheng** [comment]
如果有更新消息，咱们可以再重开这个issue
