### ISSUE TITLE
安装插件仍无法显示中文

### ISSUE THREAD

**Issue by Yoenn** [SonarQubeCommunity/sonar-l10n-zh#9]
sonarqube-6.4 + sonar-l10n-zh-plugin-1.16
将中文包放到\sonarqube-6.4\extensions\plugins, 重启sonar，进入界面仍是英文。但是查看发现显示安装了。
![chinese](https://user-images.githubusercontent.com/13333220/28814389-ed0d9702-76cf-11e7-8b77-fdee0bd94a91.png)

**Comment by xuhuisheng** [comment]
sonar根据浏览器的header选择显示的语言，一般是因为浏览器选择了英文。
Accept-Language | zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3

**Comment by Yoenn** [comment]
我的pc语言是英文，我的浏览器是chrome 59.0，设置了语言为中文，看了你的comment之后，重新查看了语言设置的是中文，将拼写检查设置的“英语（美国）“，之后发现sonar仍然显示中文，想去firefox测试一下，之后修改了firefox浏览器语言为中文，发现firefox浏览器显示仍为英文。之后再去查看chrome上，发现sonar正常显示中文了，也不知道是哪里的修改导致了显示正常。
不过还是谢谢你的回答。

**Comment by dirui412** [comment]
> sonar根据浏览器的header选择显示的语言，一般是因为浏览器选择了英文。 Accept-Language | zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
大佬 请问下是否可以设置，不管浏览器设置什么语言，强制汉化

**Comment by dirui412** [comment]
> > sonar根据浏览器的header选择显示的语言，一般是因为浏览器选择了英文。 Accept-Language | zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
> > 大佬 请问下是否可以设置，不管浏览器设置什么语言，强制汉化

@xuhuisheng

**Comment by xuhuisheng** [comment]
@dirui412 
估计要改sonarqube后端代码才行

**Comment by yangboz** [comment]
> sonar根据浏览器的header选择显示的语言，一般是因为浏览器选择了英文。 Accept-Language | zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3

如果UI界面有一个语言硬切换按钮操作就更好了
